//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPGraphvizWebPart.CodeFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SPGraphvizWebPart {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SPGraphvizWebPart() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SPGraphvizWebPart.CodeFiles.SPGraphvizWebPart", typeof(SPGraphvizWebPart).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom settings.
        /// </summary>
        internal static string Category_DisplayName {
            get {
                return ResourceManager.GetString("Category_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains css class name applied to the image.
        /// </summary>
        internal static string CssClass_Description {
            get {
                return ResourceManager.GetString("CssClass_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Css class of image.
        /// </summary>
        internal static string CssClass_DisplayName {
            get {
                return ResourceManager.GetString("CssClass_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains URL to the file with graph specified using dot language.
        /// </summary>
        internal static string DotUrl_Description {
            get {
                return ResourceManager.GetString("DotUrl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dot file URL.
        /// </summary>
        internal static string DotUrl_DisplayName {
            get {
                return ResourceManager.GetString("DotUrl_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains supported types of the image.
        /// </summary>
        internal static string ImageType_Description {
            get {
                return ResourceManager.GetString("ImageType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image type.
        /// </summary>
        internal static string ImageType_DisplayName {
            get {
                return ResourceManager.GetString("ImageType_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of supported layouts.
        /// </summary>
        internal static string LayoutType_Description {
            get {
                return ResourceManager.GetString("LayoutType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout type.
        /// </summary>
        internal static string LayoutType_DisplayName {
            get {
                return ResourceManager.GetString("LayoutType_DisplayName", resourceCulture);
            }
        }
    }
}
